# Git hooks setup wrapper script for Windows
# Auto-generated by safe git hooks installer

# Get the directory of this script
$scriptPath = Split-Path -Parent $MyInvocation.MyCommand.Path
Set-Location $scriptPath

# Check if developer-setup exists
if (-not (Test-Path "$scriptPath\developer-setup")) {
    Write-Host "Error: developer-setup directory not found!" -ForegroundColor Red
    Write-Host "Please run the safe git-hooks-installer first."
    exit 1
}

# Run the Python setup script
if (Get-Command python -ErrorAction SilentlyContinue) {
    python "$scriptPath\developer-setup\setup_githooks.py" $args
} elseif (Get-Command python3 -ErrorAction SilentlyContinue) {
    python3 "$scriptPath\developer-setup\setup_githooks.py" $args
} else {
    Write-Host "Error: Python not found! Please install Python 3." -ForegroundColor Red
    exit 1
}
