#!/bin/bash
# Git hooks setup wrapper script
# Auto-generated by safe git hooks installer

# Get the directory of this script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Check if developer-setup exists
if [ ! -d "$DIR/developer-setup" ]; then
    echo "Error: developer-setup directory not found!"
    echo "Please run the safe git-hooks-installer first."
    exit 1
fi

# Run the Python setup script
if command -v python3 &> /dev/null; then
    python3 "$DIR/developer-setup/setup_githooks.py" "$@"
elif command -v python &> /dev/null; then
    python "$DIR/developer-setup/setup_githooks.py" "$@"
else
    echo "Error: Python not found! Please install Python 3."
    exit 1
fi
