version: '3.8'

services:
  database:
    image: mariadb:10.11
    container_name: wiki-mariadb
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: my_wiki
      MYSQL_USER: wikiuser
      MYSQL_PASSWORD: example
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - wiki-network

  memcached:
    image: memcached:alpine
    container_name: wiki-memcached
    restart: unless-stopped
    networks:
      - wiki-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.9
    container_name: wiki-elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - wiki-network

  mediawiki:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: github-wiki
    restart: unless-stopped
    ports:
      - "8080:80"
    environment:
      MEDIAWIKI_DB_HOST: database
      MEDIAWIKI_DB_USER: wikiuser
      MEDIAWIKI_DB_PASSWORD: example
      MEDIAWIKI_DB_NAME: my_wiki
      MEDIAWIKI_RESTBASE_URL: http://restbase:7231
      MEDIAWIKI_SECRETKEY: "changethisinproduction"
      MEDIAWIKI_UPGRADEKEY: "changethisaswell"
    volumes:
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./content:/var/www/html/content
      - images:/var/www/html/images
      - ./extensions:/var/www/html/extensions-custom
    depends_on:
      - database
      - memcached
      - elasticsearch
    networks:
      - wiki-network

  parsoid:
    image: thenets/parsoid:0.11
    container_name: wiki-parsoid
    restart: unless-stopped
    environment:
      PARSOID_DOMAIN_localhost: http://mediawiki/api.php
    networks:
      - wiki-network

  restbase:
    image: thenets/restbase:latest
    container_name: wiki-restbase
    restart: unless-stopped
    environment:
      RB_CONF_DOMAIN: localhost
      RB_CONF_PARSOID_HOST: http://parsoid:8142
      RB_CONF_BASE_URI_TEMPLATE: http://mediawiki/api.php
      RB_CONF_API_URI_TEMPLATE: http://mediawiki/api.php
    networks:
      - wiki-network

volumes:
  db_data:
  es_data:
  images:

networks:
  wiki-network:
    driver: bridge